---
 tasks file for hetzner_storage
- name: Include OS Specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install samba related packages
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Copy credentials file
  template:
    src: hetzner_storage_box_creds.j2
    dest: "{{ credentials_file }}"

#- name: "Add mount to /etc/fstab"
#  lineinfile:
#    path: '/etc/fstab'
#    line: "//{{ storage_box_username }}.your-storagebox.de/backup {{ item.mountpoint }} cifs iocharset=utf8,rw,credentials={{ credentials_file }},uid={{ item.mount_system_user }},gid={{ item.mount_system_group }},file_mode=0660,dir_mode=0770 0 0"
#  loop: "{{ hetzner_storage_box_fstab }}"

- name: Mount up hetzner samba share
  mount:
    path: "{{ item.mountpoint }}"
    src: "//{{ storage_box_username }}.your-storagebox.de/backup"
    fstype: cifs
    opts: "iocharset=utf8,rw,credentials={{ credentials_file }},uid={{ item.mount_system_user }},gid={{ item.mount_system_group }},file_mode=0660,dir_mode=0770"
    state: mounted
  loop: "{{ hetzner_storage_box_fstab }}"

